name: Daily Lotto Bot

on:
  schedule:
    - cron: '0 3 * * *'   # 06:00 IL
    - cron: '0 6 * * *'   # 09:00 IL
    - cron: '0 9 * * *'   # 12:00 IL
    - cron: '0 12 * * *'  # 15:00 IL
    - cron: '0 15 * * *'  # 18:00 IL
    - cron: '0 18 * * *'  # 21:00 IL
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python lotto_bot.py

